- README.md
Oops, found an extra space. Can't have that! :)
> Remove stray space

- init.sh
I think this pull request is right?
This will fix perms and use a file to control it. Will solve the fact that everyone's data is currently root:root.
> Check for and fix permissions.

- README.md
> Swap a tab to spaces, say it runs on anywhere instead of unraid.

- Dockerfile
It does nothing, may as well punt it.
> Only the last CMD is used, remove this one.

- run.sh
Fixes the echo right in the middle of the no new line echo. :)
> Fix echo order.

- Dockerfile
Apparently the few intermediate containers you create during build, the better.
> Reduce number of build steps from 32 -> 16... should save space.

- README.md
Adds this option as a suggested fix to the README.
> Add run option needed to fix tmpfs mount on some distributions.

- Dockerfile
Still on the quest to make the Dockerfile more smaller.
> Collapse even more of Dockerfile.

- Dockerfile
- unifi-video.patch
The patch file needed a little modification. This is running locally for me, will let it keep going and see how it does.
> Update to v3.7.0.

- Dockerfile
I've just updated my local container to this, will see how it does.
https://community.ubnt.com/t5/UniFi-Video-Blog/bg-p/blog_airVision
> Update to v3.7.1.

- Dockerfile
And now they released 3.7.3... so here we go, running it now and will see how it does.
> Update to v3.7.3

- Dockerfile
- README.md
- unifi-video.patch
Running this locally for the next few days, we'll see how it looks.
> Update to 3.8.0

- Dockerfile
And here is 3.8.2. I *just* started running it, will see how it does.
> Update to 3.8.2

- Dockerfile
Just started running this, we'll see how it does.
> Update to 3.8.4.

- Dockerfile
Simple update; tested that the image compiles, boots and imports my backup.
> Update to 3.9.0

- Dockerfile
- README.md
Re-do ports and volumes in a more "docker" way, add #comments about what each port does from https://help.ubnt.com/hc/en-us/articles/217875218-UniFi-Video-Ports-Used
> Clean up volumes and ports in Dockerfile.

- README.md
Missed this in previous commits.
> Update README.md to change missed videos path.

- Dockerfile
- README.md
Add tagging and camera firmware downgrade to README.
> A bit of the ol' README improvements

- Dockerfile
I've currently got this running, no issues so far. Will merge to master, then probably push to release tomorrow morning.
> Update to v3.9.5.

- docker-compose.yaml
Another suggestion by @ctindel, add the apparmor option to the docker compose file w/ comment about what issue it'll fix.
> Add apparmor option to docker-compose file w/ comment about error it will fix

- docker-compose.yaml
Improve #comment a little more since @ctindel points out the example error also looks like docker compose syntax to uncomment. :)
> Refine #comment for apparmor.

- Dockerfile
Might as well have a working :beta?
> Add a beta version 3.9.6-beta.1.

- Dockerfile
Will update locally and test before merging.
> Update to v3.9.6.

- Dockerfile
May as well update baseimage...
> Update phusion/baseimage to 0.10.1.

- README.md
Forums say this is the right port.
> Add port 10001 which should allow auto detection of cameras.

- Dockerfile
> Update to 3.9.8

- Dockerfile
> Update to 3.9.8.

- Dockerfile
> Update to v3.9.11

- Dockerfile
Do the ol' 3.9.12 update. Yay.
> Update to 3.9.12.

- Dockerfile
- README.md
https://community.ubnt.com/t5/UniFi-Video-Blog/UniFi-Video-3-10-0-Soft-Release/ba-p/2656471
> Update to 3.10.1

- Dockerfile
- run.sh
This fixes up the current image on 3.4, then adds a unique commit for 3.6 and another unique one for 4.0. On master, this will go for testing. On release, I'll merge up to 3.6 and hold off the 4.0 commit until later.
> MongoDB 3.4 -> 3.6 -> 4.0 progression

- Dockerfile
- run.sh
- unifi-video.patch
This puts it at 3.10.2 for those brave souls.
> Update to 3.10.2

- Dockerfile
> update to v3.10.8

- Dockerfile
> Updated version to 3.10.11

- Dockerfile
https://community.ui.com/releases/UniFi-Video-3-10-13/7cca7ae9-f4ff-4844-a7c4-b8163bb81f21
> Update to v3.10.13
